(cl:defpackage my_robot_pck-srv
  (:use )
  (:export
   "ADDTWOINTS"
   "<ADDTWOINTS-REQUEST>"
   "ADDTWOINTS-REQUEST"
   "<ADDTWOINTS-RESPONSE>"
   "ADDTWOINTS-RESPONSE"
   "TEMPERATURECONVERTER"
   "<TEMPERATURECONVERTER-REQUEST>"
   "TEMPERATURECONVERTER-REQUEST"
   "<TEMPERATURECONVERTER-RESPONSE>"
   "TEMPERATURECONVERTER-RESPONSE"
  ))

