// Generated by gencpp from file my_robot_pkg/NavigateFeedback.msg
// DO NOT EDIT!


#ifndef MY_ROBOT_PKG_MESSAGE_NAVIGATEFEEDBACK_H
#define MY_ROBOT_PKG_MESSAGE_NAVIGATEFEEDBACK_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>

namespace my_robot_pkg
{
template <class ContainerAllocator>
struct NavigateFeedback_
{
  typedef NavigateFeedback_<ContainerAllocator> Type;

  NavigateFeedback_()
    : current_position()
    , distance_to_goal(0.0)
    , progress_percentage(0.0)
    , current_status()  {
    }
  NavigateFeedback_(const ContainerAllocator& _alloc)
    : current_position(_alloc)
    , distance_to_goal(0.0)
    , progress_percentage(0.0)
    , current_status(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _current_position_type;
  _current_position_type current_position;

   typedef float _distance_to_goal_type;
  _distance_to_goal_type distance_to_goal;

   typedef float _progress_percentage_type;
  _progress_percentage_type progress_percentage;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _current_status_type;
  _current_status_type current_status;





  typedef boost::shared_ptr< ::my_robot_pkg::NavigateFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_robot_pkg::NavigateFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct NavigateFeedback_

typedef ::my_robot_pkg::NavigateFeedback_<std::allocator<void> > NavigateFeedback;

typedef boost::shared_ptr< ::my_robot_pkg::NavigateFeedback > NavigateFeedbackPtr;
typedef boost::shared_ptr< ::my_robot_pkg::NavigateFeedback const> NavigateFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::my_robot_pkg::NavigateFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::my_robot_pkg::NavigateFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::my_robot_pkg::NavigateFeedback_<ContainerAllocator1> & lhs, const ::my_robot_pkg::NavigateFeedback_<ContainerAllocator2> & rhs)
{
  return lhs.current_position == rhs.current_position &&
    lhs.distance_to_goal == rhs.distance_to_goal &&
    lhs.progress_percentage == rhs.progress_percentage &&
    lhs.current_status == rhs.current_status;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::my_robot_pkg::NavigateFeedback_<ContainerAllocator1> & lhs, const ::my_robot_pkg::NavigateFeedback_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace my_robot_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::my_robot_pkg::NavigateFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_robot_pkg::NavigateFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_robot_pkg::NavigateFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_robot_pkg::NavigateFeedback_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_robot_pkg::NavigateFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_robot_pkg::NavigateFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::my_robot_pkg::NavigateFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6c09ee4004ed171436662289c84a7846";
  }

  static const char* value(const ::my_robot_pkg::NavigateFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6c09ee4004ed1714ULL;
  static const uint64_t static_value2 = 0x36662289c84a7846ULL;
};

template<class ContainerAllocator>
struct DataType< ::my_robot_pkg::NavigateFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_robot_pkg/NavigateFeedback";
  }

  static const char* value(const ::my_robot_pkg::NavigateFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::my_robot_pkg::NavigateFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# ── FEEDBACK ────────────────────────────────────────────────────────\n"
"geometry_msgs/Point  current_position     # Robot's current XY position\n"
"float32              distance_to_goal     # Remaining distance (m)\n"
"float32              progress_percentage  # 0.0 – 100.0\n"
"string               current_status       # e.g. \"Navigating\", \"Rotating\"\n"
"\n"
"\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
;
  }

  static const char* value(const ::my_robot_pkg::NavigateFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::my_robot_pkg::NavigateFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.current_position);
      stream.next(m.distance_to_goal);
      stream.next(m.progress_percentage);
      stream.next(m.current_status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct NavigateFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::my_robot_pkg::NavigateFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::my_robot_pkg::NavigateFeedback_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "current_position: ";
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.current_position);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "distance_to_goal: ";
    Printer<float>::stream(s, indent + "  ", v.distance_to_goal);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "progress_percentage: ";
    Printer<float>::stream(s, indent + "  ", v.progress_percentage);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "current_status: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.current_status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MY_ROBOT_PKG_MESSAGE_NAVIGATEFEEDBACK_H
