// Generated by gencpp from file my_robot_pkg/NavigateResult.msg
// DO NOT EDIT!


#ifndef MY_ROBOT_PKG_MESSAGE_NAVIGATERESULT_H
#define MY_ROBOT_PKG_MESSAGE_NAVIGATERESULT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace my_robot_pkg
{
template <class ContainerAllocator>
struct NavigateResult_
{
  typedef NavigateResult_<ContainerAllocator> Type;

  NavigateResult_()
    : success(false)
    , status_message()
    , total_distance(0.0)
    , time_elapsed(0.0)  {
    }
  NavigateResult_(const ContainerAllocator& _alloc)
    : success(false)
    , status_message(_alloc)
    , total_distance(0.0)
    , time_elapsed(0.0)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _status_message_type;
  _status_message_type status_message;

   typedef float _total_distance_type;
  _total_distance_type total_distance;

   typedef float _time_elapsed_type;
  _time_elapsed_type time_elapsed;





  typedef boost::shared_ptr< ::my_robot_pkg::NavigateResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_robot_pkg::NavigateResult_<ContainerAllocator> const> ConstPtr;

}; // struct NavigateResult_

typedef ::my_robot_pkg::NavigateResult_<std::allocator<void> > NavigateResult;

typedef boost::shared_ptr< ::my_robot_pkg::NavigateResult > NavigateResultPtr;
typedef boost::shared_ptr< ::my_robot_pkg::NavigateResult const> NavigateResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::my_robot_pkg::NavigateResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::my_robot_pkg::NavigateResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::my_robot_pkg::NavigateResult_<ContainerAllocator1> & lhs, const ::my_robot_pkg::NavigateResult_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success &&
    lhs.status_message == rhs.status_message &&
    lhs.total_distance == rhs.total_distance &&
    lhs.time_elapsed == rhs.time_elapsed;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::my_robot_pkg::NavigateResult_<ContainerAllocator1> & lhs, const ::my_robot_pkg::NavigateResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace my_robot_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::my_robot_pkg::NavigateResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_robot_pkg::NavigateResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_robot_pkg::NavigateResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_robot_pkg::NavigateResult_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_robot_pkg::NavigateResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_robot_pkg::NavigateResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::my_robot_pkg::NavigateResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9b0f48f1792e25b118436ffbff76b80e";
  }

  static const char* value(const ::my_robot_pkg::NavigateResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9b0f48f1792e25b1ULL;
  static const uint64_t static_value2 = 0x18436ffbff76b80eULL;
};

template<class ContainerAllocator>
struct DataType< ::my_robot_pkg::NavigateResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_robot_pkg/NavigateResult";
  }

  static const char* value(const ::my_robot_pkg::NavigateResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::my_robot_pkg::NavigateResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# ── RESULT ──────────────────────────────────────────────────────────\n"
"bool     success           # True if robot reached goal\n"
"string   status_message    # Human-readable status\n"
"float32  total_distance    # Path length actually travelled (m)\n"
"float32  time_elapsed      # Wall-clock time taken (s)\n"
;
  }

  static const char* value(const ::my_robot_pkg::NavigateResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::my_robot_pkg::NavigateResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
      stream.next(m.status_message);
      stream.next(m.total_distance);
      stream.next(m.time_elapsed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct NavigateResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::my_robot_pkg::NavigateResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::my_robot_pkg::NavigateResult_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "status_message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.status_message);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "total_distance: ";
    Printer<float>::stream(s, indent + "  ", v.total_distance);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "time_elapsed: ";
    Printer<float>::stream(s, indent + "  ", v.time_elapsed);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MY_ROBOT_PKG_MESSAGE_NAVIGATERESULT_H
