// Generated by gencpp from file my_robot_pkg/NavigateGoal.msg
// DO NOT EDIT!


#ifndef MY_ROBOT_PKG_MESSAGE_NAVIGATEGOAL_H
#define MY_ROBOT_PKG_MESSAGE_NAVIGATEGOAL_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/PoseStamped.h>

namespace my_robot_pkg
{
template <class ContainerAllocator>
struct NavigateGoal_
{
  typedef NavigateGoal_<ContainerAllocator> Type;

  NavigateGoal_()
    : target_pose()
    , max_speed(0.0)
    , avoid_obstacles(false)  {
    }
  NavigateGoal_(const ContainerAllocator& _alloc)
    : target_pose(_alloc)
    , max_speed(0.0)
    , avoid_obstacles(false)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::PoseStamped_<ContainerAllocator>  _target_pose_type;
  _target_pose_type target_pose;

   typedef float _max_speed_type;
  _max_speed_type max_speed;

   typedef uint8_t _avoid_obstacles_type;
  _avoid_obstacles_type avoid_obstacles;





  typedef boost::shared_ptr< ::my_robot_pkg::NavigateGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_robot_pkg::NavigateGoal_<ContainerAllocator> const> ConstPtr;

}; // struct NavigateGoal_

typedef ::my_robot_pkg::NavigateGoal_<std::allocator<void> > NavigateGoal;

typedef boost::shared_ptr< ::my_robot_pkg::NavigateGoal > NavigateGoalPtr;
typedef boost::shared_ptr< ::my_robot_pkg::NavigateGoal const> NavigateGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::my_robot_pkg::NavigateGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::my_robot_pkg::NavigateGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::my_robot_pkg::NavigateGoal_<ContainerAllocator1> & lhs, const ::my_robot_pkg::NavigateGoal_<ContainerAllocator2> & rhs)
{
  return lhs.target_pose == rhs.target_pose &&
    lhs.max_speed == rhs.max_speed &&
    lhs.avoid_obstacles == rhs.avoid_obstacles;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::my_robot_pkg::NavigateGoal_<ContainerAllocator1> & lhs, const ::my_robot_pkg::NavigateGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace my_robot_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::my_robot_pkg::NavigateGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_robot_pkg::NavigateGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_robot_pkg::NavigateGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_robot_pkg::NavigateGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_robot_pkg::NavigateGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_robot_pkg::NavigateGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::my_robot_pkg::NavigateGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "59ffd5a338ffa3347ef96f33ae41df87";
  }

  static const char* value(const ::my_robot_pkg::NavigateGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x59ffd5a338ffa334ULL;
  static const uint64_t static_value2 = 0x7ef96f33ae41df87ULL;
};

template<class ContainerAllocator>
struct DataType< ::my_robot_pkg::NavigateGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_robot_pkg/NavigateGoal";
  }

  static const char* value(const ::my_robot_pkg::NavigateGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::my_robot_pkg::NavigateGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Navigate.action\n"
"# ── GOAL ────────────────────────────────────────────────────────────\n"
"geometry_msgs/PoseStamped  target_pose      # Destination (frame_id + pose)\n"
"float32                    max_speed        # Maximum speed in m/s\n"
"bool                       avoid_obstacles  # Enable obstacle avoidance\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/PoseStamped\n"
"# A Pose with reference coordinate frame and timestamp\n"
"Header header\n"
"Pose pose\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose\n"
"# A representation of pose in free space, composed of position and orientation. \n"
"Point position\n"
"Quaternion orientation\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Point\n"
"# This contains the position of a point in free space\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::my_robot_pkg::NavigateGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::my_robot_pkg::NavigateGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.target_pose);
      stream.next(m.max_speed);
      stream.next(m.avoid_obstacles);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct NavigateGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::my_robot_pkg::NavigateGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::my_robot_pkg::NavigateGoal_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "target_pose: ";
    Printer< ::geometry_msgs::PoseStamped_<ContainerAllocator> >::stream(s, indent + "  ", v.target_pose);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "max_speed: ";
    Printer<float>::stream(s, indent + "  ", v.max_speed);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "avoid_obstacles: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.avoid_obstacles);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MY_ROBOT_PKG_MESSAGE_NAVIGATEGOAL_H
