// Generated by gencpp from file my_robot_pkg/TemperatureConverter.msg
// DO NOT EDIT!


#ifndef MY_ROBOT_PKG_MESSAGE_TEMPERATURECONVERTER_H
#define MY_ROBOT_PKG_MESSAGE_TEMPERATURECONVERTER_H

#include <ros/service_traits.h>


#include <my_robot_pkg/TemperatureConverterRequest.h>
#include <my_robot_pkg/TemperatureConverterResponse.h>


namespace my_robot_pkg
{

struct TemperatureConverter
{

typedef TemperatureConverterRequest Request;
typedef TemperatureConverterResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct TemperatureConverter
} // namespace my_robot_pkg


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::my_robot_pkg::TemperatureConverter > {
  static const char* value()
  {
    return "7737de072c8391bcef8d331fb8350e5b";
  }

  static const char* value(const ::my_robot_pkg::TemperatureConverter&) { return value(); }
};

template<>
struct DataType< ::my_robot_pkg::TemperatureConverter > {
  static const char* value()
  {
    return "my_robot_pkg/TemperatureConverter";
  }

  static const char* value(const ::my_robot_pkg::TemperatureConverter&) { return value(); }
};


// service_traits::MD5Sum< ::my_robot_pkg::TemperatureConverterRequest> should match
// service_traits::MD5Sum< ::my_robot_pkg::TemperatureConverter >
template<>
struct MD5Sum< ::my_robot_pkg::TemperatureConverterRequest>
{
  static const char* value()
  {
    return MD5Sum< ::my_robot_pkg::TemperatureConverter >::value();
  }
  static const char* value(const ::my_robot_pkg::TemperatureConverterRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::my_robot_pkg::TemperatureConverterRequest> should match
// service_traits::DataType< ::my_robot_pkg::TemperatureConverter >
template<>
struct DataType< ::my_robot_pkg::TemperatureConverterRequest>
{
  static const char* value()
  {
    return DataType< ::my_robot_pkg::TemperatureConverter >::value();
  }
  static const char* value(const ::my_robot_pkg::TemperatureConverterRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::my_robot_pkg::TemperatureConverterResponse> should match
// service_traits::MD5Sum< ::my_robot_pkg::TemperatureConverter >
template<>
struct MD5Sum< ::my_robot_pkg::TemperatureConverterResponse>
{
  static const char* value()
  {
    return MD5Sum< ::my_robot_pkg::TemperatureConverter >::value();
  }
  static const char* value(const ::my_robot_pkg::TemperatureConverterResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::my_robot_pkg::TemperatureConverterResponse> should match
// service_traits::DataType< ::my_robot_pkg::TemperatureConverter >
template<>
struct DataType< ::my_robot_pkg::TemperatureConverterResponse>
{
  static const char* value()
  {
    return DataType< ::my_robot_pkg::TemperatureConverter >::value();
  }
  static const char* value(const ::my_robot_pkg::TemperatureConverterResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MY_ROBOT_PKG_MESSAGE_TEMPERATURECONVERTER_H
