// Generated by gencpp from file my_robot_pkg/TemperatureConverterRequest.msg
// DO NOT EDIT!


#ifndef MY_ROBOT_PKG_MESSAGE_TEMPERATURECONVERTERREQUEST_H
#define MY_ROBOT_PKG_MESSAGE_TEMPERATURECONVERTERREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace my_robot_pkg
{
template <class ContainerAllocator>
struct TemperatureConverterRequest_
{
  typedef TemperatureConverterRequest_<ContainerAllocator> Type;

  TemperatureConverterRequest_()
    : celsius(0.0)  {
    }
  TemperatureConverterRequest_(const ContainerAllocator& _alloc)
    : celsius(0.0)  {
  (void)_alloc;
    }



   typedef double _celsius_type;
  _celsius_type celsius;





  typedef boost::shared_ptr< ::my_robot_pkg::TemperatureConverterRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_robot_pkg::TemperatureConverterRequest_<ContainerAllocator> const> ConstPtr;

}; // struct TemperatureConverterRequest_

typedef ::my_robot_pkg::TemperatureConverterRequest_<std::allocator<void> > TemperatureConverterRequest;

typedef boost::shared_ptr< ::my_robot_pkg::TemperatureConverterRequest > TemperatureConverterRequestPtr;
typedef boost::shared_ptr< ::my_robot_pkg::TemperatureConverterRequest const> TemperatureConverterRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::my_robot_pkg::TemperatureConverterRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::my_robot_pkg::TemperatureConverterRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::my_robot_pkg::TemperatureConverterRequest_<ContainerAllocator1> & lhs, const ::my_robot_pkg::TemperatureConverterRequest_<ContainerAllocator2> & rhs)
{
  return lhs.celsius == rhs.celsius;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::my_robot_pkg::TemperatureConverterRequest_<ContainerAllocator1> & lhs, const ::my_robot_pkg::TemperatureConverterRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace my_robot_pkg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::my_robot_pkg::TemperatureConverterRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_robot_pkg::TemperatureConverterRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_robot_pkg::TemperatureConverterRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_robot_pkg::TemperatureConverterRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_robot_pkg::TemperatureConverterRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_robot_pkg::TemperatureConverterRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::my_robot_pkg::TemperatureConverterRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ffbaa094d1bfdf2743d41684ba87c2ad";
  }

  static const char* value(const ::my_robot_pkg::TemperatureConverterRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xffbaa094d1bfdf27ULL;
  static const uint64_t static_value2 = 0x43d41684ba87c2adULL;
};

template<class ContainerAllocator>
struct DataType< ::my_robot_pkg::TemperatureConverterRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_robot_pkg/TemperatureConverterRequest";
  }

  static const char* value(const ::my_robot_pkg::TemperatureConverterRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::my_robot_pkg::TemperatureConverterRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 celsius\n"
;
  }

  static const char* value(const ::my_robot_pkg::TemperatureConverterRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::my_robot_pkg::TemperatureConverterRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.celsius);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TemperatureConverterRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::my_robot_pkg::TemperatureConverterRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::my_robot_pkg::TemperatureConverterRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "celsius: ";
    Printer<double>::stream(s, indent + "  ", v.celsius);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MY_ROBOT_PKG_MESSAGE_TEMPERATURECONVERTERREQUEST_H
