// Auto-generated. Do not edit!

// (in-package my_robot_pkg.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;
let geometry_msgs = _finder('geometry_msgs');

//-----------------------------------------------------------

class NavigateFeedback {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.current_position = null;
      this.distance_to_goal = null;
      this.progress_percentage = null;
      this.current_status = null;
    }
    else {
      if (initObj.hasOwnProperty('current_position')) {
        this.current_position = initObj.current_position
      }
      else {
        this.current_position = new geometry_msgs.msg.Point();
      }
      if (initObj.hasOwnProperty('distance_to_goal')) {
        this.distance_to_goal = initObj.distance_to_goal
      }
      else {
        this.distance_to_goal = 0.0;
      }
      if (initObj.hasOwnProperty('progress_percentage')) {
        this.progress_percentage = initObj.progress_percentage
      }
      else {
        this.progress_percentage = 0.0;
      }
      if (initObj.hasOwnProperty('current_status')) {
        this.current_status = initObj.current_status
      }
      else {
        this.current_status = '';
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type NavigateFeedback
    // Serialize message field [current_position]
    bufferOffset = geometry_msgs.msg.Point.serialize(obj.current_position, buffer, bufferOffset);
    // Serialize message field [distance_to_goal]
    bufferOffset = _serializer.float32(obj.distance_to_goal, buffer, bufferOffset);
    // Serialize message field [progress_percentage]
    bufferOffset = _serializer.float32(obj.progress_percentage, buffer, bufferOffset);
    // Serialize message field [current_status]
    bufferOffset = _serializer.string(obj.current_status, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type NavigateFeedback
    let len;
    let data = new NavigateFeedback(null);
    // Deserialize message field [current_position]
    data.current_position = geometry_msgs.msg.Point.deserialize(buffer, bufferOffset);
    // Deserialize message field [distance_to_goal]
    data.distance_to_goal = _deserializer.float32(buffer, bufferOffset);
    // Deserialize message field [progress_percentage]
    data.progress_percentage = _deserializer.float32(buffer, bufferOffset);
    // Deserialize message field [current_status]
    data.current_status = _deserializer.string(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    let length = 0;
    length += _getByteLength(object.current_status);
    return length + 36;
  }

  static datatype() {
    // Returns string type for a message object
    return 'my_robot_pkg/NavigateFeedback';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '6c09ee4004ed171436662289c84a7846';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # ── FEEDBACK ────────────────────────────────────────────────────────
    geometry_msgs/Point  current_position     # Robot's current XY position
    float32              distance_to_goal     # Remaining distance (m)
    float32              progress_percentage  # 0.0 – 100.0
    string               current_status       # e.g. "Navigating", "Rotating"
    
    
    
    ================================================================================
    MSG: geometry_msgs/Point
    # This contains the position of a point in free space
    float64 x
    float64 y
    float64 z
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new NavigateFeedback(null);
    if (msg.current_position !== undefined) {
      resolved.current_position = geometry_msgs.msg.Point.Resolve(msg.current_position)
    }
    else {
      resolved.current_position = new geometry_msgs.msg.Point()
    }

    if (msg.distance_to_goal !== undefined) {
      resolved.distance_to_goal = msg.distance_to_goal;
    }
    else {
      resolved.distance_to_goal = 0.0
    }

    if (msg.progress_percentage !== undefined) {
      resolved.progress_percentage = msg.progress_percentage;
    }
    else {
      resolved.progress_percentage = 0.0
    }

    if (msg.current_status !== undefined) {
      resolved.current_status = msg.current_status;
    }
    else {
      resolved.current_status = ''
    }

    return resolved;
    }
};

module.exports = NavigateFeedback;
