// Auto-generated. Do not edit!

// (in-package my_robot_pck.msg)


"use strict";

const _serializer = _ros_msg_utils.Serialize;
const _arraySerializer = _serializer.Array;
const _deserializer = _ros_msg_utils.Deserialize;
const _arrayDeserializer = _deserializer.Array;
const _finder = _ros_msg_utils.Find;
const _getByteLength = _ros_msg_utils.getByteLength;

//-----------------------------------------------------------

class NavigateResult {
  constructor(initObj={}) {
    if (initObj === null) {
      // initObj === null is a special case for deserialization where we don't initialize fields
      this.success = null;
      this.status_message = null;
      this.total_distance = null;
      this.time_elapsed = null;
    }
    else {
      if (initObj.hasOwnProperty('success')) {
        this.success = initObj.success
      }
      else {
        this.success = false;
      }
      if (initObj.hasOwnProperty('status_message')) {
        this.status_message = initObj.status_message
      }
      else {
        this.status_message = '';
      }
      if (initObj.hasOwnProperty('total_distance')) {
        this.total_distance = initObj.total_distance
      }
      else {
        this.total_distance = 0.0;
      }
      if (initObj.hasOwnProperty('time_elapsed')) {
        this.time_elapsed = initObj.time_elapsed
      }
      else {
        this.time_elapsed = 0.0;
      }
    }
  }

  static serialize(obj, buffer, bufferOffset) {
    // Serializes a message object of type NavigateResult
    // Serialize message field [success]
    bufferOffset = _serializer.bool(obj.success, buffer, bufferOffset);
    // Serialize message field [status_message]
    bufferOffset = _serializer.string(obj.status_message, buffer, bufferOffset);
    // Serialize message field [total_distance]
    bufferOffset = _serializer.float32(obj.total_distance, buffer, bufferOffset);
    // Serialize message field [time_elapsed]
    bufferOffset = _serializer.float32(obj.time_elapsed, buffer, bufferOffset);
    return bufferOffset;
  }

  static deserialize(buffer, bufferOffset=[0]) {
    //deserializes a message object of type NavigateResult
    let len;
    let data = new NavigateResult(null);
    // Deserialize message field [success]
    data.success = _deserializer.bool(buffer, bufferOffset);
    // Deserialize message field [status_message]
    data.status_message = _deserializer.string(buffer, bufferOffset);
    // Deserialize message field [total_distance]
    data.total_distance = _deserializer.float32(buffer, bufferOffset);
    // Deserialize message field [time_elapsed]
    data.time_elapsed = _deserializer.float32(buffer, bufferOffset);
    return data;
  }

  static getMessageSize(object) {
    let length = 0;
    length += _getByteLength(object.status_message);
    return length + 13;
  }

  static datatype() {
    // Returns string type for a message object
    return 'my_robot_pck/NavigateResult';
  }

  static md5sum() {
    //Returns md5sum for a message object
    return '9b0f48f1792e25b118436ffbff76b80e';
  }

  static messageDefinition() {
    // Returns full string definition for message
    return `
    # ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======
    # ── RESULT ──────────────────────────────────────────────────────────
    bool     success           # True if robot reached goal
    string   status_message    # Human-readable status
    float32  total_distance    # Path length actually travelled (m)
    float32  time_elapsed      # Wall-clock time taken (s)
    
    `;
  }

  static Resolve(msg) {
    // deep-construct a valid message object instance of whatever was passed in
    if (typeof msg !== 'object' || msg === null) {
      msg = {};
    }
    const resolved = new NavigateResult(null);
    if (msg.success !== undefined) {
      resolved.success = msg.success;
    }
    else {
      resolved.success = false
    }

    if (msg.status_message !== undefined) {
      resolved.status_message = msg.status_message;
    }
    else {
      resolved.status_message = ''
    }

    if (msg.total_distance !== undefined) {
      resolved.total_distance = msg.total_distance;
    }
    else {
      resolved.total_distance = 0.0
    }

    if (msg.time_elapsed !== undefined) {
      resolved.time_elapsed = msg.time_elapsed;
    }
    else {
      resolved.time_elapsed = 0.0
    }

    return resolved;
    }
};

module.exports = NavigateResult;
