// Generated by gencpp from file my_robot_pck/RobotStatus.msg
// DO NOT EDIT!


#ifndef MY_ROBOT_PCK_MESSAGE_ROBOTSTATUS_H
#define MY_ROBOT_PCK_MESSAGE_ROBOTSTATUS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace my_robot_pck
{
template <class ContainerAllocator>
struct RobotStatus_
{
  typedef RobotStatus_<ContainerAllocator> Type;

  RobotStatus_()
    : robot_name()
    , battery_level(0.0)
    , is_moving(false)
    , error_code(0)  {
    }
  RobotStatus_(const ContainerAllocator& _alloc)
    : robot_name(_alloc)
    , battery_level(0.0)
    , is_moving(false)
    , error_code(0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _robot_name_type;
  _robot_name_type robot_name;

   typedef float _battery_level_type;
  _battery_level_type battery_level;

   typedef uint8_t _is_moving_type;
  _is_moving_type is_moving;

   typedef int32_t _error_code_type;
  _error_code_type error_code;





  typedef boost::shared_ptr< ::my_robot_pck::RobotStatus_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_robot_pck::RobotStatus_<ContainerAllocator> const> ConstPtr;

}; // struct RobotStatus_

typedef ::my_robot_pck::RobotStatus_<std::allocator<void> > RobotStatus;

typedef boost::shared_ptr< ::my_robot_pck::RobotStatus > RobotStatusPtr;
typedef boost::shared_ptr< ::my_robot_pck::RobotStatus const> RobotStatusConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::my_robot_pck::RobotStatus_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::my_robot_pck::RobotStatus_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::my_robot_pck::RobotStatus_<ContainerAllocator1> & lhs, const ::my_robot_pck::RobotStatus_<ContainerAllocator2> & rhs)
{
  return lhs.robot_name == rhs.robot_name &&
    lhs.battery_level == rhs.battery_level &&
    lhs.is_moving == rhs.is_moving &&
    lhs.error_code == rhs.error_code;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::my_robot_pck::RobotStatus_<ContainerAllocator1> & lhs, const ::my_robot_pck::RobotStatus_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace my_robot_pck

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::my_robot_pck::RobotStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_robot_pck::RobotStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_robot_pck::RobotStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_robot_pck::RobotStatus_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_robot_pck::RobotStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_robot_pck::RobotStatus_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::my_robot_pck::RobotStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6cc0551541d99bdf9ecf3cda51d5c3de";
  }

  static const char* value(const ::my_robot_pck::RobotStatus_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6cc0551541d99bdfULL;
  static const uint64_t static_value2 = 0x9ecf3cda51d5c3deULL;
};

template<class ContainerAllocator>
struct DataType< ::my_robot_pck::RobotStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_robot_pck/RobotStatus";
  }

  static const char* value(const ::my_robot_pck::RobotStatus_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::my_robot_pck::RobotStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string robot_name\n"
"float32 battery_level\n"
"bool is_moving\n"
"int32 error_code\n"
;
  }

  static const char* value(const ::my_robot_pck::RobotStatus_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::my_robot_pck::RobotStatus_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.robot_name);
      stream.next(m.battery_level);
      stream.next(m.is_moving);
      stream.next(m.error_code);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RobotStatus_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::my_robot_pck::RobotStatus_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::my_robot_pck::RobotStatus_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "robot_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.robot_name);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "battery_level: ";
    Printer<float>::stream(s, indent + "  ", v.battery_level);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "is_moving: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.is_moving);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "error_code: ";
    Printer<int32_t>::stream(s, indent + "  ", v.error_code);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MY_ROBOT_PCK_MESSAGE_ROBOTSTATUS_H
