// Generated by gencpp from file my_robot_pck/TemperatureConverterResponse.msg
// DO NOT EDIT!


#ifndef MY_ROBOT_PCK_MESSAGE_TEMPERATURECONVERTERRESPONSE_H
#define MY_ROBOT_PCK_MESSAGE_TEMPERATURECONVERTERRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace my_robot_pck
{
template <class ContainerAllocator>
struct TemperatureConverterResponse_
{
  typedef TemperatureConverterResponse_<ContainerAllocator> Type;

  TemperatureConverterResponse_()
    : fahrenheit(0.0)
    , valid(false)  {
    }
  TemperatureConverterResponse_(const ContainerAllocator& _alloc)
    : fahrenheit(0.0)
    , valid(false)  {
  (void)_alloc;
    }



   typedef double _fahrenheit_type;
  _fahrenheit_type fahrenheit;

   typedef uint8_t _valid_type;
  _valid_type valid;





  typedef boost::shared_ptr< ::my_robot_pck::TemperatureConverterResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::my_robot_pck::TemperatureConverterResponse_<ContainerAllocator> const> ConstPtr;

}; // struct TemperatureConverterResponse_

typedef ::my_robot_pck::TemperatureConverterResponse_<std::allocator<void> > TemperatureConverterResponse;

typedef boost::shared_ptr< ::my_robot_pck::TemperatureConverterResponse > TemperatureConverterResponsePtr;
typedef boost::shared_ptr< ::my_robot_pck::TemperatureConverterResponse const> TemperatureConverterResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::my_robot_pck::TemperatureConverterResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::my_robot_pck::TemperatureConverterResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::my_robot_pck::TemperatureConverterResponse_<ContainerAllocator1> & lhs, const ::my_robot_pck::TemperatureConverterResponse_<ContainerAllocator2> & rhs)
{
  return lhs.fahrenheit == rhs.fahrenheit &&
    lhs.valid == rhs.valid;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::my_robot_pck::TemperatureConverterResponse_<ContainerAllocator1> & lhs, const ::my_robot_pck::TemperatureConverterResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace my_robot_pck

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::my_robot_pck::TemperatureConverterResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::my_robot_pck::TemperatureConverterResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_robot_pck::TemperatureConverterResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::my_robot_pck::TemperatureConverterResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_robot_pck::TemperatureConverterResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::my_robot_pck::TemperatureConverterResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::my_robot_pck::TemperatureConverterResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3d435f65f1f2f3d16cfcfb4341f5717c";
  }

  static const char* value(const ::my_robot_pck::TemperatureConverterResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3d435f65f1f2f3d1ULL;
  static const uint64_t static_value2 = 0x6cfcfb4341f5717cULL;
};

template<class ContainerAllocator>
struct DataType< ::my_robot_pck::TemperatureConverterResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "my_robot_pck/TemperatureConverterResponse";
  }

  static const char* value(const ::my_robot_pck::TemperatureConverterResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::my_robot_pck::TemperatureConverterResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 fahrenheit\n"
"bool valid\n"
;
  }

  static const char* value(const ::my_robot_pck::TemperatureConverterResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::my_robot_pck::TemperatureConverterResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.fahrenheit);
      stream.next(m.valid);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TemperatureConverterResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::my_robot_pck::TemperatureConverterResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::my_robot_pck::TemperatureConverterResponse_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "fahrenheit: ";
    Printer<double>::stream(s, indent + "  ", v.fahrenheit);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "valid: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.valid);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MY_ROBOT_PCK_MESSAGE_TEMPERATURECONVERTERRESPONSE_H
